server:
  port: 8080
spring:
  datasource:
    url: jdbc:sap://10.10.8.41:30015?currentschema=ADDON_MID_BASE_TEST
    username: SYSTEM
    password: Consen2018
    driver-class-name: com.sap.db.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
    path: /mdmservice/log/
    file: /mdmservice/log/service
  level:
    org:
      hibernate:
        SQL: DEBUG